<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration initiale du mini-blog.
 *
 * Une migration est une "photo" de l'evolution de la base de donnees. Doctrine
 * Migrations execute la methode up() quand on avance le schema, et la methode
 * down() si l'on annule cette version.
 *
 * Cette migration est ecrite pour PostgreSQL. Les entites PHP de src/Entity
 * restent la source de verite conceptuelle; ce fichier est la traduction SQL
 * qui permet a PostgreSQL de creer les tables, index et cles etrangeres.
 */
final class Version20260612000100 extends AbstractMigration
{
    /** Courte description affichee par doctrine:migrations:list. */
    public function getDescription(): string
    {
        return 'Initial MiniNews PostgreSQL schema for users, articles and comments';
    }

    /**
     * Cree le schema.
     *
     * addSql() enregistre une instruction SQL qui sera envoyee a PostgreSQL quand
     * on lance php bin/console doctrine:migrations:migrate.
     */
    public function up(Schema $schema): void
    {
        // Table des comptes. L'identifiant IDENTITY est l'equivalent PostgreSQL
        // d'un entier auto-incremente.
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USERS_EMAIL ON users (email)');
        $this->addSql("COMMENT ON COLUMN users.created_at IS '(DC2Type:datetime_immutable)'");

        // Table des articles. author_id pointe vers users.id: Doctrine traduit
        // la relation ManyToOne Article -> User en colonne et en contrainte SQL.
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, excerpt VARCHAR(255) NOT NULL, content TEXT NOT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23A0E66F675F31B ON article (author_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66F989D9B62 ON article (slug)');
        $this->addSql("COMMENT ON COLUMN article.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN article.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN article.published_at IS '(DC2Type:datetime_immutable)'");

        // Table des commentaires. ON DELETE CASCADE signifie que PostgreSQL
        // supprime les commentaires si leur article est supprime.
        $this->addSql('CREATE TABLE comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_id INT NOT NULL, author_id INT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9474526C7294869C ON comments (article_id)');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comments (author_id)');
        $this->addSql("COMMENT ON COLUMN comments.created_at IS '(DC2Type:datetime_immutable)'");

        // Les cles etrangeres garantissent l'integrite des relations entre tables.
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66F675F31B FOREIGN KEY (author_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_9474526C7294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES users (id)');
    }

    /**
     * Annule le schema cree par up().
     *
     * On detruit dans l'ordre inverse: contraintes, puis tables dependantes.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_9474526C7294869C');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66F675F31B');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE users');
    }
}
