<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajoute les reactions like/dislike sur les commentaires.
 *
 * Cette migration illustre une evolution classique: on ne modifie pas seulement
 * le PHP, on fait aussi evoluer la structure SQL afin que PostgreSQL puisse
 * stocker les nouvelles informations.
 */
final class Version20260612000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add comment like/dislike reactions';
    }

    public function up(Schema $schema): void
    {
        // Compteurs denormalises directement sur comments pour afficher les
        // totaux sans recompter toute la table comment_reaction a chaque page.
        $this->addSql('ALTER TABLE comments ADD like_count INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE comments ADD dislike_count INT DEFAULT 0 NOT NULL');

        // Table de reactions: une ligne represente le choix d'un utilisateur sur
        // un commentaire. value vaut 1 pour like et -1 pour dislike.
        $this->addSql('CREATE TABLE comment_reaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment_id INT NOT NULL, user_id INT NOT NULL, value INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D25A0C7F8697D13 ON comment_reaction (comment_id)');
        $this->addSql('CREATE INDEX IDX_2D25A0C7A76ED395 ON comment_reaction (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMMENT_REACTION_USER_COMMENT ON comment_reaction (comment_id, user_id)');
        $this->addSql("COMMENT ON COLUMN comment_reaction.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE comment_reaction ADD CONSTRAINT FK_2D25A0C7F8697D13 FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment_reaction ADD CONSTRAINT FK_2D25A0C7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // On annule dans l'ordre inverse: contraintes/table de reactions, puis
        // colonnes ajoutees sur comments.
        $this->addSql('ALTER TABLE comment_reaction DROP CONSTRAINT FK_2D25A0C7F8697D13');
        $this->addSql('ALTER TABLE comment_reaction DROP CONSTRAINT FK_2D25A0C7A76ED395');
        $this->addSql('DROP TABLE comment_reaction');
        $this->addSql('ALTER TABLE comments DROP like_count');
        $this->addSql('ALTER TABLE comments DROP dislike_count');
    }
}
